FROM ghcr.io/graalvm/native-image-community:23-muslib AS builder
WORKDIR /workspace
COPY build/libs/app-*-all.jar ./app.jar
RUN native-image --no-fallback --static --libc=musl -H:IncludeResources=".*" -H:Name=app -jar app.jar

FROM scratch
COPY --from=builder /workspace/app /app/app
EXPOSE 3430
ENTRYPOINT ["/app/app"]
CMD ["/app/config.yaml"]
