seed: 1647382
schemas:
  - name: society
    tables:
      - name: people
        size: 100
        columns:
          - name: id
            mode: COUNTER
          - name: firstname
            valuesBundle: forenames
          - name: lastname
            valuesBundle: surnames
          - name: birth_year
            type: 'java.lang.Integer'
            valuesRange: [1950, 2000]
          - name: birth_country
            valuesBundle: countries
          - name: occupation
            valuesResource: 'professionals.txt'
