seed: 1647382
schemas:
  - name: society
    tables:
      - name: people
        size: 100
        columns:
          - name: id
            type: 'java.math.BigInteger'
            mode: COUNTER
          - name: firstname
            type: 'java.lang.String'
            valuesResource: 'hu/webarticum/holodb/values/forenames.txt'
          - name: lastname
            type: 'java.lang.String'
            valuesResource: 'hu/webarticum/holodb/values/surnames.txt'
          - name: birth_year
            type: 'java.lang.Integer'
            valuesRange: [1950, 2000]
          - name: birth_country
            type: 'java.lang.String'
            valuesResource: 'hu/webarticum/holodb/values/countries.txt'
          - name: occupation
            type: 'java.lang.String'
            valuesResource: 'professionals.txt'
