SELECT * WHERE {
  {
    SELECT ?professionLabel
    WHERE {
      ?profession wdt:P31 wd:Q28640 .
      FILTER(EXISTS { ?profession wdt:P227 ?x })
      SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
    }
  }
  FILTER(STRLEN(?professionLabel) < 12)
  FILTER(!REGEX(?professionLabel, "^[A-Z]"))
  FILTER(REGEX(?professionLabel, "ist$"))
}
LIMIT 100